### PR TITLE
Return "text/plain" content without replacing URLs

### PR DESCRIPTION
**Pull request by webaddicto**
```php
		// Return plain text content without replacing URLs
		if(stripos($content_type, "text/plain") === 0){
			$response->setContent($str);
			return;
		}
```

Try to proxify this URL on unblockvideos.com:
https://raw.githubusercontent.com/Athlon1600/php-proxy-plugin-bundle/master/src/utils.php

Without this commit the proxy proxify all URLs.

### CODE REVIEW

**Comment by webaddicto** [comment]
@Athlon1600

What do you think about this commit?

**Comment by Athlon1600** [comment]
There is already a block of logic right after:  
	// DO NOT do any proxification on .js files  
  
that checks to see if current file is worth proxifying. That is where you should check for your content-type and if proxifying is not needed, just jump out of that method with a ```php return; ```

**Comment by webaddicto** [comment]
I updated the PR, let me know if that way is fine for you.

**Comment by Athlon1600** [comment]
Yup this is good now.

**Pull request merged**
